CREATE TABLE users (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(32),
	prefs BINARY(16)
);

CREATE TABLE video (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title TEXT,
	author FOREIGN KEY REFERENCES users(id),
	description TEXT,
	posted TIMESTAMP,
	like INTEGER,
	dislike INTEGER,
	qual BINARY(16)
)
